### ISSUE TITLE
Relative paths not working

### ISSUE THREAD

**Issue by jvolker** [davestewart/nuxt-content-assets#47]
## Background

I'm trying to get relative paths working as described in the Readme.

I'm using:
- nuxt: 3.6.5
- @nuxt/content: 2.7.2
 - nuxt-content-assets: 1.3.2

In `/content/work/myProject/index.md` I put
```
![thumbnail](thumbnail.jpg)
```

## Issue

This resolves to `<img src="thumbnail.jpg" alt="thumbnail">` so the image source points to `http://localhost:3000/work/myProject/thumbnail.jpg`, which is not returning the image but something that looks similar to the project page.

This happens with `npm run-script dev`as well as `npm run-script generate` using ProseImg and Nuxt-Image.

Any help is highly appreciated. Thanks in advance!

**Comment by davestewart** [comment]
Let me update the demo dependencies and try this.

**Comment by davestewart** [comment]
OK, just jumping back into this.

This is running as described in the [How it works](https://github.com/davestewart/nuxt-content-assets#how-it-works) section; Nitro should serve the image in `dev`, and in `build` it should be copied to the `output` folder where it loads as an asset.

What happens if you open `http://localhost:3000/work/myProject/thumbnail.jpg` in a new tab?

Do you see the image?

---

Regards "how it works" here's the built demo folder to illustrate:

![image](https://github.com/davestewart/nuxt-content-assets/assets/132681/c315f2bb-b553-47be-a62c-2b724afbde2b)

This is the image in the demo:

> ![image](https://github.com/davestewart/nuxt-content-assets/assets/132681/4c3fafe7-88ac-4e13-8b50-b1e6d2d6f13b)

Here are links to the source:

- [folder](https://github.com/davestewart/nuxt-content-assets/tree/main/demo/content/paths/italian-bean-stew)
- [file](https://raw.githubusercontent.com/davestewart/nuxt-content-assets/main/demo/content/paths/italian-bean-stew/index.md)

Is it still the case that you can

**Comment by jvolker** [comment]
Thanks for your reply. In the meantime, the demo is working again, and this also working for me as described. 

I have also updated nuxt-content-assets to 1.3.3. So I'm not sure if this was fixing it or something else.
